"""A2A message schemas."""

from contextsuite_shared.a2a.error import ErrorCode, TaskError
from contextsuite_shared.a2a.payload import TaskPayload
from contextsuite_shared.a2a.result import TaskResult
from contextsuite_shared.a2a.rpc import (
    A2A_TASK_NOT_FOUND,
    A2A_TASK_NOT_RESUMABLE,
    JSONRPC_INTERNAL_ERROR,
    JSONRPC_INVALID_PARAMS,
    JSONRPC_INVALID_REQUEST,
    JSONRPC_METHOD_NOT_FOUND,
    JSONRPC_PARSE_ERROR,
    JSONRPCError,
    JSONRPCErrorResponse,
    JSONRPCRequest,
    JSONRPCSuccessResponse,
    MessageSendConfiguration,
    MessageSendParams,
    TaskQueryParams,
)
from contextsuite_shared.a2a.status import TaskStatusUpdate
from contextsuite_shared.a2a.task import (
    Artifact,
    DataPart,
    FilePart,
    FileWithBytes,
    FileWithUri,
    Message,
    Part,
    Role,
    Task,
    TaskState,
    TaskStatus,
    TextPart,
)
from contextsuite_shared.a2a.utils import (
    artifact_from_text,
    extract_data,
    extract_text,
    message_from_text,
    model_dump,
)

__all__ = [
    "Artifact",
    "A2A_TASK_NOT_FOUND",
    "A2A_TASK_NOT_RESUMABLE",
    "DataPart",
    "ErrorCode",
    "FilePart",
    "FileWithBytes",
    "FileWithUri",
    "JSONRPCError",
    "JSONRPCErrorResponse",
    "JSONRPCRequest",
    "JSONRPCSuccessResponse",
    "JSONRPC_INTERNAL_ERROR",
    "JSONRPC_INVALID_PARAMS",
    "JSONRPC_INVALID_REQUEST",
    "JSONRPC_METHOD_NOT_FOUND",
    "JSONRPC_PARSE_ERROR",
    "Message",
    "MessageSendConfiguration",
    "MessageSendParams",
    "Part",
    "Role",
    "Task",
    "TaskError",
    "TaskPayload",
    "TaskQueryParams",
    "TaskResult",
    "TaskState",
    "TaskStatus",
    "TaskStatusUpdate",
    "TextPart",
    "artifact_from_text",
    "extract_data",
    "extract_text",
    "message_from_text",
    "model_dump",
]
